# Site settings
title: J. Alexander Branham
email: branham@utexas.edu
description: "I'm a PhD Candidate in the Department of Government at UT-Austin. I study American politics, public opinion, and methods."
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jabranham.com" # the base hostname & protocol for your site
enforce_ssl: jabranham.com
twitter_username: JAlexBranham
github_username:  jabranham
permalink: /blog/:year/:month/:title.html
google_analytics: UA-65548469-1
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima
disqus:
  shortname: jabranhamblog

# needed for CI builds:
exclude: [vendor]
